name = "audit-board-cf"
pages_build_output_dir = "dist"
compatibility_date = "2024-08-14"

[vars]
NODE_VERSION = "20"
# 强制开启 SSR 支持覆盖由于打包时的本地 nuxt.config ssr:false 配置
NUXT_SSR = "true"
# 强制开启兜底假数据以供在外部无后端直接展示效果
NUXT_PUBLIC_USE_MOCK = "true"
